[package]
name = "andrew"
version = "0.1.0"
authors = ["Lucas Timmins <timmins.s.lucas@gmail.com>"]

[dependencies]
line_drawing = "0.7.0"
bitflags = "1.0.3"
rusttype = "0.6.3"

[dev-dependencies]
smithay-client-toolkit = "0.2.6"
font-loader = "0.7.0"
